# Generated by Django 2.2.8 on 2020-02-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200122_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discord_snowflake',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='discord_username',
            field=models.CharField(blank=True, max_length=37),
        ),
        migrations.AlterField(
            model_name='team',
            name='international',
            field=models.BooleanField(default=True),
        ),
    ]
